name: deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: write

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: get-transform-run-id
      id: get_run_id
      uses: actions/github-script@v7
      with:
        script: |
          const { data: runs } = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'train.yml',
            status: 'success',
            per_page: 1,
          });
          return runs.workflow_runs[0].id;

    - name: download-model
      uses: actions/download-artifact@v4
      with:
        name: miniml-model
        path: ./models
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ steps.get_run_id.outputs.result }}

    - name: copy-model 
      run: cp -r ./models ./miniml/api/

    - name: setup-docker-buildx
      uses: docker/setup-buildx-action@v2

    - name: auth-ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build
      run: docker build -t ghcr.io/${{ github.repository }}/miniml-api:latest ./miniml/api

    - name: push
      run: docker push ghcr.io/${{ github.repository }}/miniml-api:latest