name: train

on:
  workflow_dispatch:
    inputs:
      model_id:
        description: "model-id"
        required: true
        default: "google-bert/bert-base-cased"
      batch_size:
        description: "batch-size"
        required: true
        default: 2
      iterations:
        description: "iterations"
        required: true
        default: 200
      device:
        description: "device"
        required: true
        default: "cpu"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: get-transform-run-id
      id: get_run_id
      uses: actions/github-script@v7
      with:
        script: |
          const { data: runs } = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'transform.yml',
            status: 'success',
            per_page: 1,
          });
          return runs.workflow_runs[0].id;

    - name: download-dataset
      uses: actions/download-artifact@v4
      with:
        name: miniml-data-output
        path: ./shared/
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ steps.get_run_id.outputs.result }}

    - name: docker-buildx
      uses: docker/setup-buildx-action@v2

    - name: build
      run: docker build -t miniml-train ./miniml/train

    - name: train 
      run: docker run -v ${{ github.workspace }}/shared:/shared miniml-train:latest --model-id ${{ github.event.inputs.model_id }} --train-dataset-path /shared/data/train_data --test-dataset-path /shared/data/test_data --batch-size ${{ github.event.inputs.batch_size }} --iterations ${{ github.event.inputs.iterations }} --save-model-path /shared/models/saved_model --device ${{ github.event.inputs.device }}

    - name: upload-model
      uses: actions/upload-artifact@v4
      with:
        name: miniml-model
        path: ./shared/models/
        retention-days: 3
        overwrite: true
