name: transform

on:
  workflow_dispatch:
    inputs:
      arg1:
        description: "dataset-id"
        required: true
        default: "Yelp/yelp_review_full"
      arg2:
        description: "train-test-split-ratio"
        required: true
        default: 0.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup-docker-buildx
      uses: docker/setup-buildx-action@v2

    - name: build
      run: docker build -t miniml-data ./miniml/data

    - name: transform
      run: docker run -v ${{ github.workspace }}/miniml/data/output:/app/output miniml-data --dataset-id ${{ github.event.inputs.arg1 }} --train-test-split-ratio ${{ github.event.inputs.arg2 }}

    - name: upload-data
      uses: actions/upload-artifact@v4
      with:
        name: miniml-data-output
        path: miniml/data/output/
        retention-days: 3
        overwrite: true
